## **1. Contexte**
Nous pratiquons dans ce notebook l'analyse de données sur les données provenant d'un dataset `heart attack prediction` de [Kaggle](https://kaggle.com/datasets).
Nous allons dans ce notebook explorer , visualiser et interpreter nos variables.

## **2. Imports des librairies**

Dans cette section nous allons importer les librairies principales .

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## **3. Chargement des données**
Nous allons maintenant charger notre dataset .

In [2]:
# chargement du dataset
data = pd.read_csv('../data/data.csv')

# affichage d'un extrait
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130,132,0,2,185,0,0.0,?,?,?,0
1,29,1,2,120,243,0,0,160,0,0.0,?,?,?,0
2,29,1,2,140,?,0,0,170,0,0.0,?,?,?,0
3,30,0,1,170,237,0,1,170,0,0.0,?,?,6,0
4,31,0,2,100,219,0,1,150,0,0.0,?,?,?,0

## **4. Structure et typologie des données**
Nous allons analyser la structure de notre jeu de données et le types des données et changer les types de données si nécessaires.

In [3]:
# dimension du dataset
data.shape

(294, 14)

In [4]:
# affichage des infos sur les variables et leurs types
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 294 entries, 0 to 293
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         294 non-null    int64
 1   sex         294 non-null    int64
 2   cp          294 non-null    int64
 3   trestbps    294 non-null    str
 4   chol        294 non-null    str
 5   fbs         294 non-null    str
 6   restecg     294 non-null    str
 7   thalach     294 non-null    str
 8   exang       294 non-null    str
 9   oldpeak     294 non-null    float64
 10  slope       294 non-null    str
 11  ca          294 non-null    str
 12  thal        294 non-null    str
 13  num         294 non-null    int64
dtypes: float64(1), int64(4), str(9)
memory usage: 32.3 KB

Dans l'affichage de l'extrait du dataframe dans `1.3` , nous avons remarquer que les valeurs manquantes étaient remplacées par `?`. Donc nous allons remplacer `?` par `np.nan`

In [5]:
# remplacement de ? par np.nan
data.replace('?',np.nan,inplace=True)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,28,1,2,130,132,0,2,185,0,0.0,NaN,NaN,NaN,0
1,29,1,2,120,243,0,0,160,0,0.0,NaN,NaN,NaN,0
2,29,1,2,140,NaN,0,0,170,0,0.0,NaN,NaN,NaN,0
3,30,0,1,170,237,0,1,170,0,0.0,NaN,NaN,6,0
4,31,0,2,100,219,0,1,150,0,0.0,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
289,52,1,4,160,331,0,0,94,1,2.5,NaN,NaN,NaN,1
290,54,0,3,130,294,0,1,100,1,0.0,2,NaN,NaN,1
291,56,1,4,155,342,1,0,150,1,3.0,2,NaN,NaN,1
292,58,0,2,180,393,0,0,110,1,1.0,2,NaN,7,1
293,65,1,4,130,275,0,1,115,1,1.0,2,NaN,NaN,1

Nous remarquons que tous les types devraient être des types numeriques donc nous allons les convertir.

In [6]:
# conversion des types object ou str en float ou int
data = data.apply(pd.to_numeric, errors="coerce")
data.dtypes

age             int64
sex             int64
cp              int64
trestbps      float64
chol          float64
fbs           float64
restecg       float64
thalach       float64
exang         float64
oldpeak       float64
slope         float64
ca            float64
thal          float64
num             int64
dtype: object

## **5. Préparation et nettoyage préliminaire**

### **5.1. Gestion des valeurs manquantes et des valeurs nulles**

In [7]:
# verification des valeurs nulles
data.isna().sum()

age             0
sex             0
cp              0
trestbps        1
chol           23
fbs             8
restecg         1
thalach         1
exang           1
oldpeak         0
slope         190
ca            291
thal          266
num             0
dtype: int64

In [8]:
# les variables slope , ca et that ont trop de valeurs maquantes , nous allons créer un nouveau dataset sans elles.
df = data.copy().drop(columns=['slope','ca','thal'])
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
0,28,1,2,130.0,132.0,0.0,2.0,185.0,0.0,0.0,0
1,29,1,2,120.0,243.0,0.0,0.0,160.0,0.0,0.0,0
2,29,1,2,140.0,NaN,0.0,0.0,170.0,0.0,0.0,0
3,30,0,1,170.0,237.0,0.0,1.0,170.0,0.0,0.0,0
4,31,0,2,100.0,219.0,0.0,1.0,150.0,0.0,0.0,0

In [9]:
# Nous allons attribuer aux valeurs manquantes de chol qui representent 7% du dataset la médiane , plus robuste que la moyenne
mediane =df['chol'].median()
df.fillna({'chol':mediane},inplace=True)
df['chol'].isna().sum()

np.int64(0)

In [10]:
# on peut supprimer les lignes avec des valeurs manquantes qui representent très peu dans le dataset
df=df.dropna()

In [11]:
# verification des valeurs manquantes
df.isna().sum()

age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
num           0
dtype: int64

In [12]:
# verification des valeurs nulles
df.isnull().sum()

age           0
sex           0
cp            0
trestbps      0
chol          0
fbs           0
restecg       0
thalach       0
exang         0
oldpeak       0
num           0
dtype: int64

### **5.2. Gestion des doublons**

In [13]:
# verification des valeurs dupliquées
df.duplicated().sum()

np.int64(1)

In [14]:
# affichage des valeurs dupliquées
df[df.duplicated(keep=False)]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
101,49,0,2,110.0,243.0,0.0,0.0,160.0,0.0,0.0,0
102,49,0,2,110.0,243.0,0.0,0.0,160.0,0.0,0.0,0

Dans notre contexte nous allons garder ces valeurs dupliquées car on a pas de colonne comme identifiant unique donc ces lignes pourraient concerner des patients qui sont distincts mais avec des valeurs identiques.

### **5.3. Detection et gestion des outliers**

In [15]:
# affichage des statistiques descriptives
df[['age','trestbps','chol','thalach','oldpeak']].describe()

              age    trestbps        chol     thalach     oldpeak
count  284.000000  284.000000  284.000000  284.000000  284.000000
mean    47.820423  132.725352  248.352113  139.193662    0.589085
std      7.860947   17.761731   62.963077   23.841226    0.915775
min     28.000000   92.000000   85.000000   82.000000    0.000000
25%     42.000000  120.000000  211.000000  122.000000    0.000000
50%     49.000000  130.000000  243.000000  140.000000    0.000000
75%     54.000000  140.000000  275.250000  155.000000    1.000000
max     66.000000  200.000000  603.000000  190.000000    5.000000

Nous remarquons que le maximum au niveau de `chol` est assez élevé donc nous allons investiguer en utilisant la méthode de l'IQR

In [16]:
# calcul de l'IQR
q1,q3 = np.quantile(df['chol'],q=[0.25,0.75])

# limite basse
lb = q1 - 1.5 * (q3-q1)

# limite haute
lh = q3 + 1.5 * (q3-q1)

print(f"{lb,lh=}")

lb,lh=(np.float64(114.625), np.float64(371.625))

In [17]:
df[df.chol<lb]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
128,52,1,2,140.0,100.0,0.0,0.0,138.0,1.0,0.0,0
170,56,1,4,120.0,85.0,0.0,0.0,140.0,0.0,0.0,0

In [18]:
df[df.chol>lh]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,num
70,44,1,4,150.0,412.0,0.0,0.0,170.0,0.0,0.0,0
158,55,0,2,130.0,394.0,0.0,2.0,150.0,0.0,0.0,0
225,32,1,4,118.0,529.0,0.0,0.0,130.0,0.0,0.0,1
228,40,0,4,150.0,392.0,0.0,0.0,130.0,0.0,2.0,1
243,54,1,4,130.0,603.0,1.0,0.0,125.0,1.0,1.0,1
263,52,1,4,140.0,404.0,0.0,0.0,124.0,1.0,2.0,1
265,53,1,3,145.0,518.0,0.0,0.0,130.0,0.0,0.0,1
273,56,1,4,170.0,388.0,0.0,1.0,122.0,1.0,2.0,1
281,44,1,4,135.0,491.0,0.0,0.0,135.0,0.0,0.0,1
292,58,0,2,180.0,393.0,0.0,0.0,110.0,1.0,1.0,1

Bien que ces valeurs soient extrêmes dans notre dataset, ils sont biologiquement possible . Ces lignes sont aussi très prédictifs donc nous allons les garder.

## 6. Sauvegarde du dataset nettoyé

In [20]:
df.to_csv('../data/data-cleaned.csv',index=False)